### ISSUE TITLE
electron-app-patched has no permission to open the backup asar

### ISSUE THREAD

**Issue by lockieluke** [karlhorky/electron-app-patcher#1]
<img width="728" alt="image" src="https://user-images.githubusercontent.com/25424409/209886816-4f1af493-0ee3-44e2-9037-edf7f5eed2c7.png">

**Comment by karlhorky** [comment]
@lockieluke oh interesting, maybe your shell user doesn't have access to `/Applications/Signal Beta.app`?

For me, my user (named `k`) is the owner of this file:

```bash
$ ls -al /Applications
total 0
drwxrwxr-x  46 root  admin  1472 Dec 28 17:50 .
drwxr-xr-x  20 root  wheel   640 Dec  2 12:37 ..
...
drwxr-xr-x@  3 k     staff    96 Dec 15 02:41 Signal.app
```

You could try one of either:

1. Change the ownership to this user
2. Run the `yarn patch ...` command with `sudo` beforehand, if your user is an admin user

**Comment by karlhorky** [comment]
By the way, I found that one of the recent updates to Signal broke the patch that I wrote (just indentation changed), so I fixed it:

- https://github.com/karlhorky/electron-app-patcher/commit/0deaff8c23542b2c1f0a636ad31ba6063500a519

**Comment by lockieluke** [comment]
apparently on Ventura you have to change a setting in Privacy & Security to let iTerm modify apps
![Screenshot 2023-05-13 at 14 11 22](https://github.com/karlhorky/electron-app-patcher/assets/25424409/80a87a2a-4ed0-46a5-9e4a-21268d9b1bac)

**Comment by karlhorky** [comment]
Interesting, I didn't need to do this for iTerm on Ventura  - but maybe because I have iTerm enabled under Privacy & Security -> Full Disk Access.

Anyway, glad that you got it working! Closing this issue now.
